version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - aws cloudformation package --template-file template.yaml --s3-bucket techtest-020424-artifact-store --output-template-file output-template.yaml
artifacts:
  files:
    - output-template.yaml
  discard-paths: yes