#!/usr/bin/env bash

set -e # Stop the execution of the script if it fails

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="CFN-DEPLOY"

colorize() {
  if [ "$1" == "$LABEL" ]; then
    printf "${CYAN}== $1 ${NO_COLOR}\n"
  else
    printf "${CYAN} $1 ${NO_COLOR}\n"
  fi
}

validate_variables() {
  if [ -z "$TEMPLATE_FILE" ] || [ -z "$STACK_NAME" ] || [ -z "$AWS_REGION" ]; then
    colorize "Error: Missing required variables."
    exit 1
  fi
}

validate() {
  colorize "Validating the CloudFormation template..."
  aws cloudformation validate-template --template-body file://"$TEMPLATE_FILE" --region "$AWS_REGION" 
}

deploy() {
  colorize "Deploying the CloudFormation stack..."
  aws cloudformation deploy --template-file "$TEMPLATE_FILE" --stack-name "$STACK_NAME" --capabilities "CAPABILITY_NAMED_IAM" --region "$AWS_REGION" --parameter-overrides RepositoryName="$REPOSITORY_NAME"
}


colorize "$LABEL"

# variables
TEMPLATE_FILE="template.yaml"
STACK_NAME="techtest-020424-cicd-stack"
AWS_REGION="eu-west-2"
REPOSITORY_NAME="techtest-020424-repo"

validate_variables

colorize "Validating..."
validate

colorize "Deploying..."
deploy

colorize "Deployment completed successfully!"
