version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - cd function
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - template.yaml
    - function/dist/**/*